name: pr-label-approved
on: pull_request_review

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr-label-approved:
    runs-on: ubuntu-18.04
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: '2'
          ADD_LABEL: 'Status: approved'
          REMOVE_LABEL: 'Status: Review Needed'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
